# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HalfFinishInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_id', models.CharField(max_length=32, unique=True)),
                ('half_type', models.CharField(default='半成品', max_length=16)),
                ('half_count', models.IntegerField(default=0)),
                ('half_unit_cost', models.FloatField(default=0.0)),
                ('half_unit_price', models.FloatField(default=0.0)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'syc_storage_half_finish',
            },
        ),
        migrations.CreateModel(
            name='HalfFinishRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_operate_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('half_id', models.CharField(max_length=32)),
                ('half_operate', models.CharField(max_length=8)),
                ('half_old_count', models.IntegerField(default=0)),
                ('half_new_count', models.IntegerField(default=0)),
                ('half_change_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'syc_storage_half_record',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=32, unique=True)),
                ('pro_type', models.CharField(default='包', max_length=16)),
                ('pro_count', models.IntegerField(default=0)),
                ('pro_unit_cost', models.FloatField(default=0.0)),
                ('pro_unit_price', models.FloatField(default=0.0)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'syc_storage_product_info',
            },
        ),
        migrations.CreateModel(
            name='ProductRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_operate_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('pro_id', models.CharField(max_length=32)),
                ('pro_operate', models.CharField(max_length=8)),
                ('pro_old_count', models.IntegerField(default=0)),
                ('pro_new_count', models.IntegerField(default=0)),
                ('pro_change_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'syc_storage_product_record',
            },
        ),
        migrations.CreateModel(
            name='StorageInDetailHalf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=32)),
                ('in_count', models.FloatField(default=0.0)),
                ('in_pur_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'syc_storage_in_detail_half',
            },
        ),
        migrations.CreateModel(
            name='StorageInDetailProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=32)),
                ('in_count', models.FloatField(default=0.0)),
                ('in_pur_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'syc_storage_in_detail_product',
            },
        ),
        migrations.CreateModel(
            name='StorageInHalf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_total_count', models.FloatField(default=0.0)),
                ('in_date', models.DateField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'syc_storage_in_half',
            },
        ),
        migrations.CreateModel(
            name='StorageInProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_total_count', models.FloatField(default=0.0)),
                ('in_date', models.DateField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'syc_storage_in_product',
            },
        ),
        migrations.CreateModel(
            name='StorageOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_id', models.IntegerField(default=0, unique=True)),
                ('storage_create_date', models.DateTimeField(auto_now_add=True)),
                ('storage_price', models.FloatField(default=0.0)),
                ('storage_actual_price', models.FloatField(default=0.0)),
                ('pur_handler', models.CharField(max_length=256)),
                ('pur_comment', models.CharField(max_length=32)),
                ('cust_id', models.IntegerField(default=0)),
                ('translation_expense', models.FloatField(default=0.0)),
                ('translation_comment', models.CharField(max_length=256)),
                ('rebate', models.IntegerField(default=0)),
                ('is_enough', models.BooleanField(default=False)),
                ('is_out', models.BooleanField(default=0)),
                ('payment_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'syc_storage_out',
            },
        ),
        migrations.CreateModel(
            name='StorageOutDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=32)),
                ('storage_pro_count', models.IntegerField(default=0)),
                ('storage_pro_actual_price', models.FloatField(default=0.0)),
                ('storage_pro_price', models.FloatField(default=0.0)),
                ('pur_id', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'syc_storage_out_detail',
            },
        ),
    ]
