# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageout',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
