# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(default=0)),
                ('pur_id', models.IntegerField(default=0)),
                ('ref_pur_id', models.IntegerField(default=0)),
                ('flow_type', models.CharField(max_length=32)),
                ('cash_change', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('is_enough', models.BooleanField(default=False)),
                ('flow_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'syc_report_cashflow',
            },
        ),
        migrations.CreateModel(
            name='CustomerRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(default=0)),
                ('pur_count', models.IntegerField(default=0)),
                ('balance', models.FloatField(default=0.0)),
                ('latest_pur_date', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'syc_report_customer_rank',
            },
        ),
        migrations.CreateModel(
            name='StatementOutputDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(default=0)),
                ('origin_balance', models.FloatField(default=0.0)),
                ('pur_id', models.IntegerField(default=0)),
                ('pur_actual_price', models.FloatField(default=0.0)),
                ('ref_pur_id', models.IntegerField(default=0)),
                ('ref_pur_price', models.IntegerField(default=0)),
                ('income', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'syc_statement_output_detail',
            },
        ),
    ]
