# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_price', models.FloatField(default=0.0)),
                ('pur_create_date', models.DateTimeField(auto_now_add=True)),
                ('pur_modify_date', models.DateField(default='2019-04-12')),
                ('pur_finished_date', models.DateField(auto_now=True)),
                ('pur_handle', models.CharField(max_length=256)),
                ('pur_comment', models.CharField(max_length=32)),
                ('cust_id', models.IntegerField(default=1)),
                ('rebate', models.IntegerField(default=0)),
                ('pur_status', models.CharField(default='0', max_length=8)),
                ('payment_status', models.BooleanField(default=0)),
                ('predict_freight', models.IntegerField(default=0)),
                ('is_enough', models.BooleanField(default=0)),
                ('is_selected', models.BooleanField(default=0)),
                ('is_finished', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'syc_purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=32)),
                ('pur_pro_count', models.IntegerField(default=0)),
                ('pur_pro_price', models.FloatField(default=0.0)),
                ('pur_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'syc_pur_detail',
            },
        ),
        migrations.CreateModel(
            name='RefundPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('ref_cust_id', models.IntegerField(default=0)),
                ('rebate', models.FloatField(default=0.0)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'syc_refund_purchase',
            },
        ),
        migrations.CreateModel(
            name='RefundPurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_pro_id', models.CharField(max_length=32)),
                ('ref_pro_count', models.IntegerField(default=1)),
                ('ref_purchase_id', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'syc_refund_purchase_detail',
            },
        ),
    ]
