# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pur_modify_date',
            field=models.DateField(default='2019-05-20'),
        ),
    ]
