# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20190520_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pur_modify_date',
            field=models.DateField(default='2019-06-01'),
        ),
    ]
