# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20190601_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pur_modify_date',
            field=models.DateField(default='2019-06-04'),
        ),
    ]
