# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=16)),
                ('plan_pro_id', models.CharField(max_length=16)),
                ('plan_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'syc_plan_detail',
            },
        ),
        migrations.CreateModel(
            name='PlanList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
            ],
            options={
                'db_table': 'syc_plan',
            },
        ),
    ]
