# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('telephone_number', models.CharField(default='', max_length=32)),
                ('level', models.IntegerField(default=5)),
                ('comment', models.CharField(default='', max_length=256)),
                ('password', models.CharField(default='', max_length=512)),
                ('load_in_token', models.CharField(default='', max_length=512)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'syc_user_info',
            },
        ),
    ]
